name: Go Auto Tag & Release

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v -o tyu-diskmark ./...

    - name: Create Tag
      id: tag_step
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        TAG="v$(date +'%Y%m%d-%H%M%S')"
        git tag "$TAG"
        git push origin "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: GH Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        tag_name: ${{ steps.tag_step.outputs.tag }}
        name: Release ${{ steps.tag_step.outputs.tag }}
        body: |
          This is an automated release.
          Commit: ${{ github.sha }}
        files: |
          tyu-diskmark
