# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
    
    - name: GH Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          This is an automated release.

          Changes:
          - Built from tag ${{ github.ref_name }}
          - Commit: ${{ github.sha }}
        # 上传的文件
        files: |
          tyu-diskmark
          # dist/bundle.js    # 可以添加多个文件
        prerelease: false

      
